services:
  discord-bot:
    build: .
    container_name: discord-music-bot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    networks:
      - bot-network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
        reservations:
          memory: 256M
          cpus: "0.25"

networks:
  bot-network:
    driver: bridge

volumes:
  logs:
